### PR TITLE
Feature/bird objects

### PR DESCRIPTION
**Pull request by Alibaba000101**
added birds to the sidebar

### CODE REVIEW

**Review by DimitarIM — CHANGES_REQUESTED** [review]
Birds.js requires a variable with the parent element for it to generate the buttons on the sidebar. Currently it doesn't. Everything else seems good enough.

**Comment by Alibaba000101** [comment]
> Birds.js requires a variable with the parent element for it to generate the buttons on the sidebar. Currently it doesn't. Everything else seems good enough.

It's on there... check line 50.

**Review by andre84o — CHANGES_REQUESTED** [review]
The JS link needs to move to top between or removes

**Review by andre84o — APPROVED** [review]
LG

**Review by DimitarIM — APPROVED** [review]
LGTM

**Pull request merged**
